version: '3.7'
services:
  postgres:
    network_mode: "host"
    container_name: postgres
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    logging:
      options:
        max-size: 10m
        max-file: "3"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/init.sql:/docker-entrypoint-initdb.d/sql/init.sql

  crud:
    network_mode: "host"
    build: .
    container_name: crud
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=mydb
      - DB_SSLMODE=disable
      - DB_PASSWORD=root
    restart: always
